//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsolClient.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.Attend[] AttendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.UserDetail DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.Event[] EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.Attend[] Attends {
            get {
                return this.AttendsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendsField, value) != true)) {
                    this.AttendsField = value;
                    this.RaisePropertyChanged("Attends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.UserDetail Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetail", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class UserDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attend", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class Attend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.Event EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool willAttendField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.Event Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool willAttend {
            get {
                return this.willAttendField;
            }
            set {
                if ((this.willAttendField.Equals(value) != true)) {
                    this.willAttendField = value;
                    this.RaisePropertyChanged("willAttend");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.Attend[] AttendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.User OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsolClient.ServiceReference2.Post[] PostsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.Attend[] Attends {
            get {
                return this.AttendsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendsField, value) != true)) {
                    this.AttendsField = value;
                    this.RaisePropertyChanged("Attends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsolClient.ServiceReference2.Post[] Posts {
            get {
                return this.PostsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostsField, value) != true)) {
                    this.PostsField = value;
                    this.RaisePropertyChanged("Posts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WriterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostID {
            get {
                return this.PostIDField;
            }
            set {
                if ((this.PostIDField.Equals(value) != true)) {
                    this.PostIDField = value;
                    this.RaisePropertyChanged("PostID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Writer {
            get {
                return this.WriterField;
            }
            set {
                if ((object.ReferenceEquals(this.WriterField, value) != true)) {
                    this.WriterField = value;
                    this.RaisePropertyChanged("Writer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAttend", Namespace="http://schemas.datacontract.org/2004/07/LocalService.Model")]
    [System.SerializableAttribute()]
    public partial class UserAttend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AttendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Attends {
            get {
                return this.AttendsField;
            }
            set {
                if ((this.AttendsField.Equals(value) != true)) {
                    this.AttendsField = value;
                    this.RaisePropertyChanged("Attends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializeDataBase", ReplyAction="http://tempuri.org/IService1/InitializeDataBaseResponse")]
        void InitializeDataBase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializeDataBase", ReplyAction="http://tempuri.org/IService1/InitializeDataBaseResponse")]
        System.Threading.Tasks.Task InitializeDataBaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        TestConsolClient.ServiceReference2.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmailTaken", ReplyAction="http://tempuri.org/IService1/EmailTakenResponse")]
        bool EmailTaken(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmailTaken", ReplyAction="http://tempuri.org/IService1/EmailTakenResponse")]
        System.Threading.Tasks.Task<bool> EmailTakenAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersOfEvent", ReplyAction="http://tempuri.org/IService1/GetUsersOfEventResponse")]
        TestConsolClient.ServiceReference2.User[] GetUsersOfEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersOfEvent", ReplyAction="http://tempuri.org/IService1/GetUsersOfEventResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User[]> GetUsersOfEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        TestConsolClient.ServiceReference2.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByPassword", ReplyAction="http://tempuri.org/IService1/GetUserByPasswordResponse")]
        TestConsolClient.ServiceReference2.User GetUserByPassword(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByPassword", ReplyAction="http://tempuri.org/IService1/GetUserByPasswordResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetUserByPasswordAsync(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventsOwner", ReplyAction="http://tempuri.org/IService1/GetEventsOwnerResponse")]
        TestConsolClient.ServiceReference2.User GetEventsOwner(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventsOwner", ReplyAction="http://tempuri.org/IService1/GetEventsOwnerResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetEventsOwnerAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        TestConsolClient.ServiceReference2.User CreateUser(TestConsolClient.ServiceReference2.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> CreateUserAsync(TestConsolClient.ServiceReference2.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        TestConsolClient.ServiceReference2.User UpdateUser(int id, TestConsolClient.ServiceReference2.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> UpdateUserAsync(int id, TestConsolClient.ServiceReference2.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPosts", ReplyAction="http://tempuri.org/IService1/GetPostsResponse")]
        TestConsolClient.ServiceReference2.Post[] GetPosts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPosts", ReplyAction="http://tempuri.org/IService1/GetPostsResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post[]> GetPostsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByID", ReplyAction="http://tempuri.org/IService1/GetPostByIDResponse")]
        TestConsolClient.ServiceReference2.Post GetPostByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByID", ReplyAction="http://tempuri.org/IService1/GetPostByIDResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> GetPostByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostsByEvent", ReplyAction="http://tempuri.org/IService1/GetPostsByEventResponse")]
        TestConsolClient.ServiceReference2.Post[] GetPostsByEvent(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostsByEvent", ReplyAction="http://tempuri.org/IService1/GetPostsByEventResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post[]> GetPostsByEventAsync(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePost", ReplyAction="http://tempuri.org/IService1/CreatePostResponse")]
        TestConsolClient.ServiceReference2.Post CreatePost(TestConsolClient.ServiceReference2.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePost", ReplyAction="http://tempuri.org/IService1/CreatePostResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> CreatePostAsync(TestConsolClient.ServiceReference2.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        void DeletePost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        System.Threading.Tasks.Task DeletePostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePost", ReplyAction="http://tempuri.org/IService1/UpdatePostResponse")]
        TestConsolClient.ServiceReference2.Post UpdatePost(int id, TestConsolClient.ServiceReference2.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePost", ReplyAction="http://tempuri.org/IService1/UpdatePostResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> UpdatePostAsync(int id, TestConsolClient.ServiceReference2.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEvents", ReplyAction="http://tempuri.org/IService1/GetEventsResponse")]
        TestConsolClient.ServiceReference2.Event[] GetEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEvents", ReplyAction="http://tempuri.org/IService1/GetEventsResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event[]> GetEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventById", ReplyAction="http://tempuri.org/IService1/GetEventByIdResponse")]
        TestConsolClient.ServiceReference2.Event GetEventById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventById", ReplyAction="http://tempuri.org/IService1/GetEventByIdResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> GetEventByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventsOfUser", ReplyAction="http://tempuri.org/IService1/GetEventsOfUserResponse")]
        TestConsolClient.ServiceReference2.Event[] GetEventsOfUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEventsOfUser", ReplyAction="http://tempuri.org/IService1/GetEventsOfUserResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event[]> GetEventsOfUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEvent", ReplyAction="http://tempuri.org/IService1/CreateEventResponse")]
        TestConsolClient.ServiceReference2.Event CreateEvent(TestConsolClient.ServiceReference2.Event even);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEvent", ReplyAction="http://tempuri.org/IService1/CreateEventResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> CreateEventAsync(TestConsolClient.ServiceReference2.Event even);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEvent", ReplyAction="http://tempuri.org/IService1/DeleteEventResponse")]
        void DeleteEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEvent", ReplyAction="http://tempuri.org/IService1/DeleteEventResponse")]
        System.Threading.Tasks.Task DeleteEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEvent", ReplyAction="http://tempuri.org/IService1/UpdateEventResponse")]
        TestConsolClient.ServiceReference2.Event UpdateEvent(int eventId, TestConsolClient.ServiceReference2.Event even);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEvent", ReplyAction="http://tempuri.org/IService1/UpdateEventResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> UpdateEventAsync(int eventId, TestConsolClient.ServiceReference2.Event even);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAttend", ReplyAction="http://tempuri.org/IService1/IsAttendResponse")]
        bool IsAttend(int userId, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAttend", ReplyAction="http://tempuri.org/IService1/IsAttendResponse")]
        System.Threading.Tasks.Task<bool> IsAttendAsync(int userId, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrUpdateAttend", ReplyAction="http://tempuri.org/IService1/CreateOrUpdateAttendResponse")]
        void CreateOrUpdateAttend(TestConsolClient.ServiceReference2.Attend attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrUpdateAttend", ReplyAction="http://tempuri.org/IService1/CreateOrUpdateAttendResponse")]
        System.Threading.Tasks.Task CreateOrUpdateAttendAsync(TestConsolClient.ServiceReference2.Attend attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAttend", ReplyAction="http://tempuri.org/IService1/CreateAttendResponse")]
        TestConsolClient.ServiceReference2.Attend CreateAttend(TestConsolClient.ServiceReference2.Attend attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAttend", ReplyAction="http://tempuri.org/IService1/CreateAttendResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Attend> CreateAttendAsync(TestConsolClient.ServiceReference2.Attend attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAttend", ReplyAction="http://tempuri.org/IService1/DeleteAttendResponse")]
        void DeleteAttend(int userId, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAttend", ReplyAction="http://tempuri.org/IService1/DeleteAttendResponse")]
        System.Threading.Tasks.Task DeleteAttendAsync(int userId, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComplexUsersOfEvent", ReplyAction="http://tempuri.org/IService1/GetComplexUsersOfEventResponse")]
        TestConsolClient.ServiceReference2.UserAttend[] GetComplexUsersOfEvent(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComplexUsersOfEvent", ReplyAction="http://tempuri.org/IService1/GetComplexUsersOfEventResponse")]
        System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.UserAttend[]> GetComplexUsersOfEventAsync(int eventID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestConsolClient.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestConsolClient.ServiceReference2.IService1>, TestConsolClient.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeDataBase() {
            base.Channel.InitializeDataBase();
        }
        
        public System.Threading.Tasks.Task InitializeDataBaseAsync() {
            return base.Channel.InitializeDataBaseAsync();
        }
        
        public TestConsolClient.ServiceReference2.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public bool EmailTaken(string email) {
            return base.Channel.EmailTaken(email);
        }
        
        public System.Threading.Tasks.Task<bool> EmailTakenAsync(string email) {
            return base.Channel.EmailTakenAsync(email);
        }
        
        public TestConsolClient.ServiceReference2.User[] GetUsersOfEvent(int eventId) {
            return base.Channel.GetUsersOfEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User[]> GetUsersOfEventAsync(int eventId) {
            return base.Channel.GetUsersOfEventAsync(eventId);
        }
        
        public TestConsolClient.ServiceReference2.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public TestConsolClient.ServiceReference2.User GetUserByPassword(string email, string psw) {
            return base.Channel.GetUserByPassword(email, psw);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetUserByPasswordAsync(string email, string psw) {
            return base.Channel.GetUserByPasswordAsync(email, psw);
        }
        
        public TestConsolClient.ServiceReference2.User GetEventsOwner(int eventId) {
            return base.Channel.GetEventsOwner(eventId);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> GetEventsOwnerAsync(int eventId) {
            return base.Channel.GetEventsOwnerAsync(eventId);
        }
        
        public TestConsolClient.ServiceReference2.User CreateUser(TestConsolClient.ServiceReference2.User user) {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> CreateUserAsync(TestConsolClient.ServiceReference2.User user) {
            return base.Channel.CreateUserAsync(user);
        }
        
        public void DeleteUser(int id) {
            base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public TestConsolClient.ServiceReference2.User UpdateUser(int id, TestConsolClient.ServiceReference2.User user) {
            return base.Channel.UpdateUser(id, user);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.User> UpdateUserAsync(int id, TestConsolClient.ServiceReference2.User user) {
            return base.Channel.UpdateUserAsync(id, user);
        }
        
        public TestConsolClient.ServiceReference2.Post[] GetPosts() {
            return base.Channel.GetPosts();
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post[]> GetPostsAsync() {
            return base.Channel.GetPostsAsync();
        }
        
        public TestConsolClient.ServiceReference2.Post GetPostByID(int id) {
            return base.Channel.GetPostByID(id);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> GetPostByIDAsync(int id) {
            return base.Channel.GetPostByIDAsync(id);
        }
        
        public TestConsolClient.ServiceReference2.Post[] GetPostsByEvent(int eventID) {
            return base.Channel.GetPostsByEvent(eventID);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post[]> GetPostsByEventAsync(int eventID) {
            return base.Channel.GetPostsByEventAsync(eventID);
        }
        
        public TestConsolClient.ServiceReference2.Post CreatePost(TestConsolClient.ServiceReference2.Post post) {
            return base.Channel.CreatePost(post);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> CreatePostAsync(TestConsolClient.ServiceReference2.Post post) {
            return base.Channel.CreatePostAsync(post);
        }
        
        public void DeletePost(int id) {
            base.Channel.DeletePost(id);
        }
        
        public System.Threading.Tasks.Task DeletePostAsync(int id) {
            return base.Channel.DeletePostAsync(id);
        }
        
        public TestConsolClient.ServiceReference2.Post UpdatePost(int id, TestConsolClient.ServiceReference2.Post post) {
            return base.Channel.UpdatePost(id, post);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Post> UpdatePostAsync(int id, TestConsolClient.ServiceReference2.Post post) {
            return base.Channel.UpdatePostAsync(id, post);
        }
        
        public TestConsolClient.ServiceReference2.Event[] GetEvents() {
            return base.Channel.GetEvents();
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event[]> GetEventsAsync() {
            return base.Channel.GetEventsAsync();
        }
        
        public TestConsolClient.ServiceReference2.Event GetEventById(int id) {
            return base.Channel.GetEventById(id);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> GetEventByIdAsync(int id) {
            return base.Channel.GetEventByIdAsync(id);
        }
        
        public TestConsolClient.ServiceReference2.Event[] GetEventsOfUser(int userId) {
            return base.Channel.GetEventsOfUser(userId);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event[]> GetEventsOfUserAsync(int userId) {
            return base.Channel.GetEventsOfUserAsync(userId);
        }
        
        public TestConsolClient.ServiceReference2.Event CreateEvent(TestConsolClient.ServiceReference2.Event even) {
            return base.Channel.CreateEvent(even);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> CreateEventAsync(TestConsolClient.ServiceReference2.Event even) {
            return base.Channel.CreateEventAsync(even);
        }
        
        public void DeleteEvent(int eventId) {
            base.Channel.DeleteEvent(eventId);
        }
        
        public System.Threading.Tasks.Task DeleteEventAsync(int eventId) {
            return base.Channel.DeleteEventAsync(eventId);
        }
        
        public TestConsolClient.ServiceReference2.Event UpdateEvent(int eventId, TestConsolClient.ServiceReference2.Event even) {
            return base.Channel.UpdateEvent(eventId, even);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Event> UpdateEventAsync(int eventId, TestConsolClient.ServiceReference2.Event even) {
            return base.Channel.UpdateEventAsync(eventId, even);
        }
        
        public bool IsAttend(int userId, int eventId) {
            return base.Channel.IsAttend(userId, eventId);
        }
        
        public System.Threading.Tasks.Task<bool> IsAttendAsync(int userId, int eventId) {
            return base.Channel.IsAttendAsync(userId, eventId);
        }
        
        public void CreateOrUpdateAttend(TestConsolClient.ServiceReference2.Attend attend) {
            base.Channel.CreateOrUpdateAttend(attend);
        }
        
        public System.Threading.Tasks.Task CreateOrUpdateAttendAsync(TestConsolClient.ServiceReference2.Attend attend) {
            return base.Channel.CreateOrUpdateAttendAsync(attend);
        }
        
        public TestConsolClient.ServiceReference2.Attend CreateAttend(TestConsolClient.ServiceReference2.Attend attend) {
            return base.Channel.CreateAttend(attend);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.Attend> CreateAttendAsync(TestConsolClient.ServiceReference2.Attend attend) {
            return base.Channel.CreateAttendAsync(attend);
        }
        
        public void DeleteAttend(int userId, int eventId) {
            base.Channel.DeleteAttend(userId, eventId);
        }
        
        public System.Threading.Tasks.Task DeleteAttendAsync(int userId, int eventId) {
            return base.Channel.DeleteAttendAsync(userId, eventId);
        }
        
        public TestConsolClient.ServiceReference2.UserAttend[] GetComplexUsersOfEvent(int eventID) {
            return base.Channel.GetComplexUsersOfEvent(eventID);
        }
        
        public System.Threading.Tasks.Task<TestConsolClient.ServiceReference2.UserAttend[]> GetComplexUsersOfEventAsync(int eventID) {
            return base.Channel.GetComplexUsersOfEventAsync(eventID);
        }
    }
}
